logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug
spring:
  rabbitmq:
    host: 192.168.10.100
    virtual-host: /
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        prefetch: 1
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
#    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型(simple:同步阻塞， correlated:异步回调)
#    publisher-returns: true # 开启publisher return机制