logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.10.100
    virtual-host: /
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto #自动处理【默认】
        retry:
          enabled: true
          # 下面都是默认配置
          max-attempts: 3
          initial-interval: 1000 # 初始的失败等待时长为1秒
          multiplier: 3 # 失败的等待时长倍数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false